<?php
$textcolor='#000000';
$linkcolor='#FFFFFF';
$bgcolor='#ffffff';
$tableborder='#ffcc00';
$timeout='24';
$ip_file='d:/appserv/www/poll/ip.txt';
$font='arial';
$fontsize='2';
$datafile='d:/appserv/www/poll/data.txt';
$option='10';
$use_image='0';
$image_for_vote='';
?>